# Generated by Django 4.1.1 on 2022-09-26 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profiles_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='Address',
            new_name='address',
        ),
    ]
