# Generated by Django 4.1.1 on 2022-10-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_requests_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='profile_image',
            field=models.ImageField(blank=True, default='default profile.jpg', null=True, upload_to='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='requests',
            name='document_type',
            field=models.CharField(blank=True, choices=[('Brgy. Clearance', 'Brgy. Clearance'), ('Certificate of Ingency', 'Certificate of Ingency')], max_length=1000, null=True),
        ),
    ]
