# Generated by Django 4.1.1 on 2022-10-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_profiles_gender_alter_profiles_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='profile_image',
            field=models.ImageField(blank=True, default='default profile.jpg', null=True, upload_to=''),
        ),
    ]
