# Generated by Django 4.1.1 on 2022-10-08 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_profiles_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='owner',
        ),
        migrations.AddField(
            model_name='requests',
            name='is_read',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='profiles.profiles'),
        ),
        migrations.AddField(
            model_name='requests',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.profiles'),
        ),
    ]
