# Generated by Django 4.1.1 on 2022-10-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='your_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
