# Generated by Django 4.1.1 on 2022-11-13 09:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_profiles_vaccine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='vaccine',
            field=models.CharField(blank=True, choices=[('Vaccinated', 'Vaccinated'), ('Not Vaccinated', 'Not Vaccinated')], max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Verificationss',
            fields=[
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('brgy_id', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_read', models.BooleanField(default=False, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='profiles.profiles')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profiles')),
            ],
            options={
                'ordering': ['is_read', '-date_created'],
            },
        ),
    ]
