# Generated by Django 4.1.1 on 2022-11-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_alter_profiles_vaccine_verificationss'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
