# Generated by Django 4.1.1 on 2022-11-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_alter_profiles_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
