# Generated by Django 4.1.1 on 2022-11-21 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_profiles_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
