# Generated by Django 4.1.1 on 2022-11-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_requests_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='username',
        ),
        migrations.AddField(
            model_name='requests',
            name='receiver_username',
            field=models.CharField(blank=True, editable=False, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='sender_username',
            field=models.CharField(blank=True, editable=False, max_length=1000, null=True),
        ),
    ]
