# Generated by Django 4.1.1 on 2022-11-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_remove_requests_username_requests_receiver_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='receiver_username',
            field=models.CharField(blank=True, editable=False, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='sender_username',
            field=models.CharField(blank=True, editable=False, max_length=1000, null=True),
        ),
    ]
