# Generated by Django 4.1.1 on 2022-11-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_messages_receiver_username_messages_sender_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='receiver_username',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='sender_username',
        ),
        migrations.AddField(
            model_name='reports',
            name='receiver_username',
            field=models.CharField(blank=True, editable=False, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='reports',
            name='sender_username',
            field=models.CharField(blank=True, editable=False, max_length=1000, null=True),
        ),
    ]
