# Generated by Django 4.1.1 on 2022-11-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_remove_messages_receiver_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='hide',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
