# Generated by Django 4.1.1 on 2022-11-25 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0030_requests_hide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requests',
            options={'ordering': ['is_read', 'hide', '-date_created']},
        ),
    ]
