# Generated by Django 4.1.1 on 2022-11-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0032_alter_requests_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='hide',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
