# Generated by Django 4.1.1 on 2022-12-04 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0034_userextendmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserExtendModel',
        ),
    ]
