# Generated by Django 4.1.1 on 2022-12-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0035_delete_userextendmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='village',
            field=models.CharField(blank=True, choices=[('Crisville', 'Crisville'), ('Gulod', 'Gulod'), ('Matandang Barrio', 'Matandang Barrio'), ('Mataas na Kahoy', 'Mataas na Kahoy'), ('Katuparan', 'Katuparan'), ('Kaypiskal', 'Kaypiskal'), ('Sulucan', 'Sulucan'), ('NHV', 'NHV')], max_length=500, null=True),
        ),
    ]
