# Generated by Django 4.1.1 on 2022-12-05 04:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0036_profiles_village'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkInProfiles',
            fields=[
                ('profile_image', models.ImageField(blank=True, default='default profile.jpg', null=True, upload_to='')),
                ('username', models.CharField(blank=True, max_length=500, null=True)),
                ('first_name', models.CharField(blank=True, max_length=500, null=True)),
                ('last_name', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=500, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=500, null=True)),
                ('vaccine', models.CharField(blank=True, choices=[('Vaccinated', 'Vaccinated'), ('Not Vaccinated', 'Not Vaccinated')], max_length=500, null=True)),
                ('verified', models.BooleanField(default=False, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('village', models.CharField(blank=True, choices=[('Crisville', 'Crisville'), ('Gulod', 'Gulod'), ('Matandang Barrio', 'Matandang Barrio'), ('Mataas na Kahoy', 'Mataas na Kahoy'), ('Katuparan', 'Katuparan'), ('Kaypiskal', 'Kaypiskal'), ('Sulucan', 'Sulucan'), ('NHV', 'NHV')], max_length=500, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profiles')),
            ],
        ),
    ]
