# Generated by Django 4.1.1 on 2022-12-05 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0037_walkinprofiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walkinprofiles',
            name='username',
        ),
    ]
