# Generated by Django 4.1.1 on 2022-12-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0039_remove_messages_your_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='blk_unit',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='phase_street',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='document_type',
            field=models.CharField(blank=True, choices=[('Brgy. Clearance', 'Brgy. Clearance'), ('Certificate of Indigency', 'Certificate of Indigency')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='document_type',
            field=models.CharField(blank=True, choices=[('Brgy. Clearance', 'Brgy. Clearance'), ('Certificate of Indigency', 'Certificate of Indigency')], max_length=1000, null=True),
        ),
    ]
