# Generated by Django 4.1.1 on 2022-12-13 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0040_profiles_blk_unit_profiles_phase_street_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='address',
        ),
    ]
