# Generated by Django 4.1.1 on 2022-12-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0043_verificationss_verify_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationss',
            name='verify_message',
        ),
    ]
