# Generated by Django 4.1.1 on 2022-12-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0045_sendmessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmessages',
            name='message',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
