# Generated by Django 4.1.1 on 2022-12-13 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0046_alter_sendmessages_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmessages',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_message', to='profiles.profiles'),
        ),
    ]
