# Generated by Django 4.1.1 on 2022-12-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0047_alter_sendmessages_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='done',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='done',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
