# Generated by Django 4.1.1 on 2022-12-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0048_reports_done_requests_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationss',
            name='done',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
