# Generated by Django 4.1.1 on 2022-12-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0049_verificationss_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='suffix',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='walkinprofiles',
            name='suffix',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
