# Generated by Django 4.1.1 on 2022-12-15 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0052_reports_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remark_owner', to='profiles.profiles'),
        ),
    ]
