# Generated by Django 4.1.1 on 2022-12-15 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0055_remove_reports_receiver_remove_reports_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='profiles.profiles'),
        ),
        migrations.AddField(
            model_name='reports',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profiles'),
        ),
    ]
