# Generated by Django 4.1.1 on 2022-12-15 15:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0056_reports_receiver_reports_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkInRequests',
            fields=[
                ('owner_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('document_type', models.CharField(blank=True, choices=[('Brgy. Clearance', 'Brgy. Clearance'), ('Certificate of Indigency', 'Certificate of Indigency')], max_length=1000, null=True)),
                ('purpose', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_read', models.BooleanField(default=False, null=True)),
                ('hide', models.BooleanField(default=False, null=True)),
                ('done', models.BooleanField(default=False, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
