# Generated by Django 4.1.1 on 2022-12-15 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0057_walkinrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkinrequests',
            name='made_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profiles'),
        ),
    ]
