# Generated by Django 4.1.1 on 2022-12-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0058_walkinrequests_made_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='sender',
            new_name='made_by',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='receiver_username',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='sender_username',
        ),
        migrations.AddField(
            model_name='requests',
            name='owner_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
