# Generated by Django 4.1.1 on 2022-12-15 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0059_rename_sender_requests_made_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='made_by',
            new_name='sender',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='owner_name',
        ),
        migrations.AddField(
            model_name='requests',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request', to='profiles.profiles'),
        ),
        migrations.AddField(
            model_name='requests',
            name='receiver_username',
            field=models.CharField(blank=True, editable=False, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='sender_username',
            field=models.CharField(blank=True, editable=False, max_length=1000, null=True),
        ),
    ]
