# Generated by Django 4.1.1 on 2022-12-15 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0062_remove_walkinrequests_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkinrequests',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.walkinprofiles'),
        ),
    ]
