# Generated by Django 4.1.1 on 2022-09-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_officials_alter_events_featured_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officials',
            name='profile_image',
            field=models.ImageField(blank=True, default='default profile.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='events',
            name='featured_image',
            field=models.ImageField(blank=True, default='default thumbnail.png', null=True, upload_to=''),
        ),
    ]
