# Generated by Django 4.1.1 on 2022-09-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_officials_profile_image_alter_events_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='featured_image',
            field=models.ImageField(blank=True, default='default thumbnail.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='officials',
            name='profile_image',
            field=models.ImageField(blank=True, default='default profile.jpg', null=True, upload_to=''),
        ),
    ]
