# Generated by Django 4.1.1 on 2022-09-24 03:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_news_featured_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkOfficials',
            fields=[
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('position', models.CharField(blank=True, max_length=1000, null=True)),
                ('profile_image', models.ImageField(blank=True, default='default profile.jpg', null=True, upload_to='')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Officials',
            new_name='BrgyOfficials',
        ),
    ]
